version: v0.7.1-alpha.1

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
        min_password_length: 6
        identifier_similarity_check_enabled: false
    link:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:3000/auth/error
    logout:
      after:
        default_browser_return_url: http://localhost:3000/auth/login
    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m
    registration:
      ui_url: http://localhost:3000/auth/registration
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://host.docker.internal:3001/kratos/register
              method: POST
              body: file:///etc/config/kratos/register_legacy.jsonnet
              auth:
                type: api_key
                config:
                  name: x-kratos-key
                  value: api.serlo.org-kratos-secret
                  in: header
    verification:
      enabled: true
      ui_url: http://localhost:3000/auth/verification
    recovery:
      enabled: true
      ui_url: http://localhost:3000/auth/recovery
    settings:
      ui_url: http://localhost:3000/auth/settings
log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
  template_override_path: /etc/config/kratos/email-templates/
  templates:
    verification:
      valid:
        email:
          subject: http://host.docker.internal:3000/api/.ory/mail-templates/verification/valid/email.subject.gotmpl
          body:
            html: http://host.docker.internal:3000/api/.ory/mail-templates/verification/valid/email.body.gotmpl
            plaintext: http://host.docker.internal:3000/api/.ory/mail-templates/verification/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: http://host.docker.internal:3000/api/.ory/mail-templates/verification/invalid/email.subject.gotmpl
          body:
            html: http://host.docker.internal:3000/api/.ory/mail-templates/verification/invalid/email.body.gotmpl
            plaintext: http://host.docker.internal:3000/api/.ory/mail-templates/verification/invalid/email.body.plaintext.gotmpl
    recovery:
      valid:
        email:
          subject: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/valid/email.subject.gotmpl
          body:
            html: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/valid/email.body.gotmpl
            plaintext: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/invalid/email.subject.gotmpl
          body:
            html: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/invalid/email.body.gotmpl
            plaintext: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/invalid/email.body.plaintext.gotmpl
