version: '3.7'
services:
  kratos-migrate:
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: .
        target: /etc/config/kratos
    command: -c /etc/config/kratos/config.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/config.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: .
        target: /etc/config/kratos
    networks:
      - intranet
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
  hydra:
    image: oryd/hydra:v1.11.8
    ports:
      - '4444:4444'
      - '4445:4445'
    command: serve all --dangerous-force-http
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
    environment:
      - LOG_LEVEL=debug
      - LOG_LEAK_SENSITIVE_VALUES=true
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_LOGIN=http://localhost:3001/hydra/login
      - URLS_LOGOUT=http://localhost:3001/hydra/logout
      - URLS_CONSENT=http://localhost:3001/hydra/consent
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
    networks:
      - intranet
  # Uncomment when testing user import
  # import-users-job:
  #   depends_on:
  #     - kratos-migrate
  #     - kratos
  #   image: node:16
  #   volumes:
  #     - ./import-users.js:/tmp/import-users.js
  #   working_dir: /tmp
  #   command: "bash -c 'yarn init --yes && yarn add mysql @ory/client && node import-users.js'"
  #   restart: on-failure
  #   networks:
  #     - intranet
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  redis:
    image: redis:6.0
    restart: always
    ports:
      - '6379:6379'
    networks:
      - intranet
  api:
    image: eu.gcr.io/serlo-shared/api-server:0.47.0-staging.7
    command: yarn start
    depends_on:
      - redis
    ports:
      - '3001:3001'
    environment:
      - ENVIRONMENT="local"
      - REDIS_URL=redis://redis:6379
      - SERLO_ORG_DATABASE_LAYER_HOST=db-layer:8080
      - SERLO_ORG_SECRET=serlo.org-secret
      - SERVER_HYDRA_HOST=http://hydra:4445
      - SERVER_KRATOS_PUBLIC_HOST=http://kratos:4433
      - SERVER_KRATOS_ADMIN_HOST=http://kratos:4434
      - SERVER_KRATOS_SECRET=api.serlo.org-kratos-secret
      - SERVER_SERLO_CLOUDFLARE_WORKER_SECRET="api.serlo.org-playground-secret"
      - SERVER_SERLO_CACHE_WORKER_SECRET="api.serlo.org-cache-worker-secret"
      - SERVER_SWR_QUEUE_DASHBOARD_PASSWORD="secret"
    networks:
      - intranet
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - intranet
  db-layer:
    image: eu.gcr.io/serlo-shared/serlo-org-database-layer:0.3.52
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    command: ./server
    environment:
      - DATABASE_MAX_CONNECTIONS=5
      - DATABASE_URL=mysql://root:secret@mysql:3306/serlo
      - ENV=development
    networks:
      - intranet
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    restart: on-failure
    environment:
      MONGO_URL: 'mongodb://mongodb:27017/rocketchat?replicaSet=rs0'
      MONGO_OPLOG_URL: 'mongodb://mongodb:27017/local?replicaSet=rs0'
      ROOT_URL: http://localhost:3030
      PORT: '3030'
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
    expose:
      - '3030'
    ports:
      - '${BIND_IP:-0.0.0.0}:${HOST_PORT:-3030}:3030'
    networks:
      - intranet
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
      - ./dump:/dump
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: '27017'
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: '27017'
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: 'true'
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-sqlite:
  hydra-sqlite:
  mongodb_data: { driver: local }
